---
kind: pipeline
type: docker
name: verify
steps:
- name: install
  image: danlynn/ember-cli:5.8.0-node_20.12
  commands:
  - npm ci
- name: lint
  image: danlynn/ember-cli:5.8.0-node_20.12
  commands:
  - npm run lint
- name: dependency-lint
  image: danlynn/ember-cli:5.8.0-node_20.12
  commands:
  - ember dependency-lint
- name: test
  image: danlynn/ember-cli:5.8.0-node_20.12
  commands:
  - npm run test:ember
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-gelinkt-notuleren
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: eqZ7xv8p/lyEuKiNorcbYdZFmlkZab3pDWZUdmDq2frKrb1WBv0qew==
---
kind: secret
name: docker_password
data: 9gIVFfRe6fST03CLSukPobVBNntis/JVzfJ9ytbXjPhfsP6FWVxLq9Y/lQ==
---
kind: signature
hmac: 8aa13c8fab152c9ec612a1943122a258c652092674009112a1f18150cb8261c6

...
